import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/SessionProvider";

import Header from "@/component/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose as needed
  variable: "--font-poppins",
});



export const metadata: Metadata = {
  title: "FitnessFREAK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <SessionWrapper>
          
          <Header/>
         

          
          <main className="min-h-screen">{children}</main>
        </SessionWrapper>
      </body>
    </html>
  );
}
